name: ci

on:
  pull_request:
  push:
    branches:
      - main

concurrency: "ci-${{ github.ref }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nemerosa'

      - name: Configure npm for GitHub Packages
        run: |
          echo "@nemerosa:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Install dependencies
        id: npm-ci
        run: npm ci

      - name: Building and running tests
        id: npm-build
        run: npm run build && npm test

        # Testing the action

      - name: "Test: download"
        id: test-download
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Test: getting the version"
        id: test-version
        run: |
          ./yontrack version --cli

      - name: Publication
        id: npm-publish
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
